### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by m4ttr4ymond** [alexhkurz/programming-languages-2019#1]
Lecture 1.2 says `Exp     ::=     Exp     "+"     Exp1  | Exp 1`, and I think it should actually say `Exp     ::=     Exp     "+"     Exp  | Exp 1`. I might be wrong though.

**Comment by alexhkurz** [comment]
Very good question.

And thanks for hunting for typos, I am keen to improve my notes in any possible way. 

But this time it was on purpose. 

Remember the question of how many parse trees you have for 

  1+2+3+4

if the grammar contains the line

 Exp ::= Exp "+" Exp 

?

And now try the same with 

  Exp ::= Exp "+" Exp1

instead.

Looking forward to more questions ...

All the best,

Alexander

PS Let me know if you get this email as reply-to is not your email address ... not sure how this is supposed to work ...

**Comment by alexhkurz** [comment]
Ok, I think I get it now ... we communicate via github and you get a notification if I reply ... good system as all students can see the questions and my replies.

**Comment by m4ttr4ymond** [comment]
> Very good question. And thanks for hunting for typos, I am keen to improve my notes in any possible way. But this time it was on purpose. Remember the question of how many parse trees you have for 1+2+3+4 if the grammar contains the line Exp ::= Exp "+" Exp ? And now try the same with Exp ::= Exp "+" Exp1 instead. Looking forward to more questions ... All the best, Alexander PS Let me know if you get this email as reply-to is not your email address ... not sure how this is supposed to work ...
> […](#)
> On Aug 30, 2019, at 10:43, Matt Raymond ***@***.***> wrote: Lecture 1.2 says Exp ::= Exp "+" Exp1 | Exp 1, and I think it should actually say Exp ::= Exp "+" Exp | Exp 1. I might be wrong though. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Why are we using `Exp1 | Exp1` instead of just `Exp1` if "[The | is used to separate alternative definitions and is interpreted as "or"](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form)"? Wouldn't `Exp ::= Exp "+" Exp1 | Exp1` be redundant?

**Comment by alexhkurz** [comment]
`Exp ::= Exp "+" Exp1 | Exp1` abbreviates

    Exp ::= Exp "+" Exp1 
    Exp ::= Exp1

Does this help?

If we just had  Exp1 instead of Exp1 | Exp1 we would just have the first rule, but not the second. But without the second rule, we couldnt parse `2*3`.

**Comment by m4ttr4ymond** [comment]
Ohhh, ok. Thank you so much. I was reading it as Exp ::= Exp "+" (Exp1 |
Exp1) instead of Exp ::= (Exp "+" Exp1) | Exp1

Thank for clarifying!
Matt Raymond

**Comment by alexhkurz** [comment]
Thanks for the question ... instructively, the misunderstanding was caused by you parsing the grammar (written for parsing arithmetic expressions) differently ...
