### ISSUE TITLE
Issue with Pseudocode for sorting?

### ISSUE THREAD

**Issue by raymo116** [alexhkurz/programming-languages-2019#10]
Professor Kurtz,

I tried to implement it in python to make sure that I understood it, and the algorithm doesn't seem to work. Am I reading the pseudocode wrong?

If this is the algorithm:
```
sort #  =  #
sort n:l  =  insert n l

insert n #  =  n:#
insert n m:l  =
    n smaller equal to m -> n:m:l
    otherwise -> m:(insert n l)
```

Then this would be the code implementation:
```
def sort(list):
    if(len(list) == 1):
        return [item]
    else:
        return insert(list[0], list[1:])

def insert(item, list):
    if(len(list) == 1):
        return [item] + list
    else:
        if(item <= list[0]):
            return [item] + list
        else:
            return [list[0]] + insert(item + list[1:])

print(sort([2, 3, 1, 4]))
```
which returns `[2, 3, 1, 4]`. I think is probably because of the line `n smaller equal to m -> n:m:l`, which, with the list `2:(3:(1:#))`, would operate as `2 smaller equal to 3 -> 2:3:1`. Since there's no other function call, `2:3:1` would be the exit condition and there would be no further checks.

**Comment by alexhkurz** [comment]
Thanks you right ... as I wrote it sort wouldnt be recursive, so couldnt possibly work ... I corrected it

Alexander
