### ISSUE TITLE
Issue with is a member output?

### ISSUE THREAD

**Issue by jgonz100** [alexhkurz/programming-languages-2019#11]
I finished writing my member.lc program and was testing the example input in the README.
As expected, "member a a : b:#" produces "S 0" because a is the first element of the list and is therefore a member, but, the example of "member S 0 0:S 0:#" should produce false is confusing. If we are testing if S 0 is in 0:S 0:# then the elements of l are 0 and S 0 so
member S 0 0:S 0:# should return true, or S 0 as it does in my program, am I correct in thinking this?

**Comment by alexhkurz** [comment]
Thanks for spotting this ... corrected ... can you check?

Alexander
