### ISSUE TITLE
BNCF install instructions don't include required cabal command.

### ISSUE THREAD

**Issue by jhburns** [alexhkurz/programming-languages-2019#3]
Following along the tutorial here: https://github.com/alexhkurz/programming-languages-2019/blob/master/BNFC-installation.md#working-under-linuxmacos, specifically this section:
```
git clone https://github.com/BNFC/bnfc
cd bnfc  
make
```
I got the following error: `Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal update' to download it` when running `make`.

So I think the command `cabal update` should be inbetween `cd bnfc` and `make` to prevent the error for other people.

**Comment by alexhkurz** [comment]
Thanks ... this may be different for different users ... I added a comment ...
