### ISSUE TITLE
Lambda Calculus Examples

### ISSUE THREAD

**Issue by welle108** [alexhkurz/programming-languages-2019#6]
Found this section a little unclear:

    \x.x -- the identity function that returns its argument
    \x.\y.x -- the function that takes two arguments and returns the first
    \x.\y.y -- the function that takes two arguments and returns the second

After looking around I found a stackexchange answer that explains it really well if anyone else is stuck:

https://cs.stackexchange.com/questions/56314/lambda-calculus-argument-delimiter

**Comment by welle108** [comment]
As the post says, the \x. \y. is syntactic sugaring to make it easier to read

**Comment by alexhkurz** [comment]
I would explain it like this:

We introduced rules that allow us to drop parentheses.

According to these rules, we know that

    \x.\y.x 

is short for 

    \x.(\y.x)

If you want to call dropping parentheses syntactic sugar, I agree with your statement.

But "syntactic sugar" is usually reserved for more substantial abbreviations.

For example, we commonly say that

    \ x y . z

is syntactic sugar for 

    \ x . \ y . z

but this is an abbreviation that I have not yet introduced.

Thanks for the question.

Alexander
