### ISSUE TITLE
The le example for Assignment1 is wrong

### ISSUE THREAD

**Issue by theorangepotato** [alexhkurz/programming-languages-2019#9]
The [le example](https://github.com/alexhkurz/programming-languages-2019/tree/master/Assignment1#assignment1ble-1-out-of-15) in Assignment1 says that it should return `S 0` iff the first argument is less than or equal to the second, thus *both* examples listed should return `S 0`, not just the second. If you switch the order of the arguments in the first example, it will be true.

**Comment by alexhkurz** [comment]
thanks ... corrected (please check)

A

**Comment by theorangepotato** [comment]
Looks good to me!
